// Espelha os enums do Prisma schema para uso no frontend/backend sem depender do @prisma/client

export enum Role {
  MOTORISTA = 'MOTORISTA',
  TRANSPORTADORA_ADMIN = 'TRANSPORTADORA_ADMIN',
  TRANSPORTADORA_OPERACIONAL = 'TRANSPORTADORA_OPERACIONAL',
  TRANSPORTADORA_FINANCEIRO = 'TRANSPORTADORA_FINANCEIRO',
  EMBARCADOR = 'EMBARCADOR',
  PLATFORM_ADMIN = 'PLATFORM_ADMIN',
  API_CONSUMER = 'API_CONSUMER',
}

export enum CheckinStatus {
  AWAITING_APPOINTMENT = 'AWAITING_APPOINTMENT',
  AWAITING_CHECKOUT = 'AWAITING_CHECKOUT',
  CERTIFICATE_ISSUED = 'CERTIFICATE_ISSUED',
  TITLE_GENERATED = 'TITLE_GENERATED',
  CANCELLED = 'CANCELLED',
}

export enum TituloStatus {
  ISSUED = 'ISSUED',
  PAID = 'PAID',
  CONTESTED = 'CONTESTED',
  PROTESTED = 'PROTESTED',
  JUDICIAL = 'JUDICIAL',
  CANCELLED = 'CANCELLED',
}

export enum CausaType {
  EMBARCADOR = 'EMBARCADOR',
  DESTINATARIO = 'DESTINATARIO',
  TERMINAL = 'TERMINAL',
  OUTROS = 'OUTROS',
}

export enum PlanoType {
  FREE = 'FREE',
  PRO = 'PRO',
  BUSINESS = 'BUSINESS',
  ENTERPRISE = 'ENTERPRISE',
}

export enum AssinaturaStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  CANCELLED = 'CANCELLED',
  PAST_DUE = 'PAST_DUE',
}

export enum PagamentoMetodo {
  CARTAO_CREDITO = 'CARTAO_CREDITO',
  BOLETO = 'BOLETO',
  PIX = 'PIX',
  FATURA = 'FATURA',
}

export enum WebhookEvent {
  CHECKIN_CREATED = 'CHECKIN_CREATED',
  CHECKOUT_COMPLETED = 'CHECKOUT_COMPLETED',
  CERTIFICATE_ISSUED = 'CERTIFICATE_ISSUED',
  TITULO_GERADO = 'TITULO_GERADO',
  TITULO_PAGO = 'TITULO_PAGO',
  TITULO_CONTESTADO = 'TITULO_CONTESTADO',
  ALERTA_OVERBOOKING = 'ALERTA_OVERBOOKING',
  SCORE_ATUALIZADO = 'SCORE_ATUALIZADO',
}
